# Generated by Django 2.2 on 2019-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.IntegerField(),
        ),
    ]
