# Generated by Django 2.2 on 2019-04-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190414_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entry'),
        ),
    ]
