# Generated by Django 2.2 on 2019-04-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190414_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_images', to='api.Entry'),
        ),
    ]
